# Generated by Django 5.0.4 on 2024-04-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_category_options_alter_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
