# Generated by Django 5.0.3 on 2024-05-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='product_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
