# Generated by Django 5.0.3 on 2024-05-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_notification_product_name_notification_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='quantity',
        ),
    ]
